import { useParams } from 'react-router-dom';
import { Building2 } from 'lucide-react';
import { ARCHITECT_PROFILE, PORTFOLIO_EVIDENCE } from '@/constants';

/**
 * Dynamic Pitch page — Blueprint § 2 / § 5.3: `/vip/:companyId`.
 *
 * Phase 1 renders the static scaffold from the local evidence source so the
 * route and layout are real. Phase 3 replaces the data source with
 * `GET /api/pitch/{companyId}`, which returns the tailored cover letter and
 * the company-specific project selection, and records the recruiter view.
 */
export default function VipPitchPage() {
  const { companyId } = useParams<{ companyId: string }>();
  const featured = PORTFOLIO_EVIDENCE.slice(0, 3);

  return (
    <div className="min-h-screen bg-[#07080c] text-zinc-200 px-6 py-16">
      <div className="max-w-4xl mx-auto space-y-12">
        <header className="space-y-3">
          <div className="flex items-center gap-2 text-amber-400">
            <Building2 className="w-4 h-4" />
            <span className="text-xs font-mono uppercase tracking-[0.25em]">
              Prepared for {companyId}
            </span>
          </div>
          <h1 className="text-4xl font-bold text-white">
            {ARCHITECT_PROFILE.fullName}
          </h1>
          <p className="text-zinc-400">{ARCHITECT_PROFILE.title}</p>
        </header>

        <section className="border border-zinc-800 bg-zinc-950/60 rounded-2xl p-6">
          <h2 className="text-xs font-mono uppercase tracking-wider text-zinc-500 mb-3">
            Tailored Cover Letter
          </h2>
          <p className="text-sm text-zinc-500 leading-relaxed">
            Generated by the Tailor Agent in Phase 4 and approved in the Pitch
            Studio before this link is shared.
          </p>
        </section>

        <section className="space-y-5">
          <h2 className="text-xs font-mono uppercase tracking-wider text-zinc-500">
            Selected Evidence
          </h2>
          {featured.map((p) => (
            <article
              key={p.projectId}
              className="border border-zinc-800 bg-zinc-950/60 rounded-2xl p-6 space-y-4"
            >
              <div>
                <h3 className="text-white font-semibold text-lg">
                  {p.identity.title}
                </h3>
                <p className="text-xs font-mono text-amber-400/70">
                  {p.identity.category} · {p.identity.status}
                </p>
              </div>
              <dl className="space-y-3 text-sm">
                <div>
                  <dt className="text-zinc-600 text-xs uppercase font-mono">
                    Challenge
                  </dt>
                  <dd className="text-zinc-400 leading-relaxed">
                    {p.decisionLog.challenge}
                  </dd>
                </div>
                <div>
                  <dt className="text-zinc-600 text-xs uppercase font-mono">
                    Decision
                  </dt>
                  <dd className="text-zinc-400 leading-relaxed">
                    {p.decisionLog.decision}
                  </dd>
                </div>
                <div>
                  <dt className="text-zinc-600 text-xs uppercase font-mono">
                    Outcome
                  </dt>
                  <dd className="text-zinc-400 leading-relaxed">
                    {p.decisionLog.outcome}
                  </dd>
                </div>
              </dl>
              <ul className="flex flex-wrap gap-2 pt-1">
                {p.softwareStack.map((s) => (
                  <li
                    key={s}
                    className="text-[11px] font-mono text-zinc-500 border border-zinc-800 rounded px-2 py-1"
                  >
                    {s}
                  </li>
                ))}
              </ul>
            </article>
          ))}
        </section>

        <footer className="border-t border-zinc-900 pt-6 text-sm text-zinc-500 space-y-1">
          <p>{ARCHITECT_PROFILE.email}</p>
          <p>{ARCHITECT_PROFILE.phone}</p>
        </footer>
      </div>
    </div>
  );
}
